#include "Includes\AutomatingWindowsExplorer.au3"

Opt( "MustDeclareVars", 1 )

Example()

Func Example()
  ; Windows Explorer on XP, Vista, 7, 8
  Local $hExplorer = WinGetHandle( "[REGEXPCLASS:^(Cabinet|Explore)WClass$]" )
  If Not $hExplorer Then
    MsgBox( 0, "Automating Windows Explorer", "Could not find Windows Explorer. Terminating." )
    Return
  EndIf

  ; Get an IShellBrowser interface
  GetIShellBrowser( $hExplorer )
  If Not IsObj( $oIShellBrowser ) Then
    MsgBox( 0, "Automating Windows Explorer", "Could not get an IShellBrowser interface. Terminating." )
    Return
  EndIf

  ; Get other interfaces
  GetShellInterfaces()

  ; Get current icon view
  Local $view = GetIconView()

  Local $iView, $iSize
  If IsArray( $view ) Then ; OS > XP
    $iView = $view[0] ; Icon view
    $iSize = $view[1] ; Icon size
    If $iView <> $FVM_DETAILS Then    ; Not details view
      SetIconView( $FVM_DETAILS, 16 ) ; Set details view
    ElseIf $iView <> $FVM_ICON Then   ; Not icon view
      SetIconView( $FVM_ICON, 48 )    ; Set icon view
    EndIf
    Sleep( 3000 )                     ; Wait 3 seconds
    SetIconView( $iView, $iSize )     ; Restore old view

  Else ; OS = XP
    $iView = $view
    If $iView <> $FVM_DETAILS Then    ; Not details view
      SetIconView( $FVM_DETAILS )     ; Set details view
    ElseIf $iView <> $FVM_ICON Then   ; Not icon view
      SetIconView( $FVM_ICON )        ; Set icon view
    EndIf
    Sleep( 3000 )                     ; Wait 3 seconds
    SetIconView( $iView )             ; Restore old view
  EndIf
